### ISSUE TITLE
Integrate documentation/methodology

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#2]
[HEADS Methodology](https://heads-project.github.io/methodology) should also be available from within Eclipse.

One option is to directly use the web-browser embedded into Eclipse.

**Comment by brice-morin** [comment]
I think @barais fixed that

**Comment by barais** [comment]
yes, done

2015-03-03 14:47 GMT+01:00 Brice Morin <notifications@github.com>:
