### ISSUE TITLE
Operation on message param leads to C compilation error

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/heads_ide#21]
This operation will generate faulty C code 
			
    transition -> Init
    event m : from_ender?pif_token
    action do
        to_starter!pif_token(m.token-1)
    end

If not allowed, this should lead to HEADS-IDE error message

**Comment by brice-morin** [comment]
@Lyadis is that still an issue? If yes, is that fixable?

**Comment by Lyadis** [comment]
No I think it is fixed.
