### ISSUE TITLE
A more flexible print function is wanted

### ISSUE THREAD

**Issue by sdalgard** [HEADS-project/heads_ide#23]
The ThingML print function can only print a string
More flexibility is wanted, at least printing numbers

**Comment by brice-morin** [comment]
Also related to Issue #44 

Custom prints and other utility functions not directly supported in the language should be defined by users as function, which could be reused across things (defining such behavior as asynchronous with ports and messages rapidly becomes messy and implies an overhead (queue, etc))

**Comment by brice-morin** [comment]
With the TypeChecker, we can now print most types (that we can statically determine) using the normal print function.
