### ISSUE TITLE
Problems building generated Maven projects within HEADS IDE on Mac OS

### ISSUE THREAD

**Issue by mboussaa** [HEADS-project/heads_ide#24]
When I try to compile to Java code, Eclipse does still spinning and then crashes so I have to restart it, but I can find the generated java code in my workspace. However, it works fine for other compilers. I am using Heads IDE Eclipse, Mac OS and the HelloWorld example.

**Comment by brice-morin** [comment]
I close this issue as it seems to be a problem with Maven + Eclipse + MacOS, far beyond HEADS responsibilities. Again, generated code can be managed in any IDE or CLI.
