### ISSUE TITLE
[ThingML] Refactor generated Javascript targeting Node.js

### ISSUE THREAD

**Issue by maxleiko** [HEADS-project/heads_ide#25]
Generated javascript for the Node.js platform should be refactored so that it produces a proper npm module.  

The generated `state.js` library in `lib/state.js` is available in the `npm` registry.  
The generated state.js wrapper at the beginning of `behavior.js` should be externalized as an npm module.  

**For instance:**  
  - You should create your own `thingml-state` module that depends on `state.js`, and publish it to the `npm` registry.  
  - You should only generate your `behavior.js` that uses `thingml-state`
  - You should add a generated `package.json` at the root of the `javascript/` folder

**The overall generated code base should look like this:**  
  - js-gen/
    - package.json
    - helloworld.js (this might be named after the name of the .thingml file, not 'behavior.js' no?)

**Samples:**  
`package.json`
```json
{
 "name": "thing-helloworld",
 "version": "1.0.0",
 "description": "HelloWorld thing generated from ThingML",
 "main": "helloworld.js",
 "dependencies": {
   "thingml-state": "^X.Y.Z"
 }
}
```

`helloworld.js`
```js
var ThingMLState = require('thingml-state');

/**
 * Definition for type : HelloThing
 **/
function HelloThing() {
  // ...
  // state machine (states and regions)
  // DONT DO this.HelloThing_HelloWorld
  // no one is using upper case for their attributes :D
  this.helloworld_region = ThingMLState.buildRegion("HelloWorld");
  // ...
}
```

About the `Connector` function, it might also need its own module (?)

**Comment by brice-morin** [comment]
I think the new structure is OK and way modular than it use to be. Thanks for the hints @maxleiko
