### ISSUE TITLE
Stop on components is not called on SIGINT

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#53]
It seems (at least on Windows) that the stop on each individual components is not called on SIGINT. Unlike the outputs showed in Exercice 1 of the Java tutorial, I do not get the *Bye, world!* that is supposed to be displayed by the stop method. This can be problematic in more complex examples, where some resources (ports, files, etc) might not be properly closed...

**Comment by brice-morin** [comment]
Seems that it works using PowerShell, but not with GitBash...... strange!

**Comment by brice-morin** [comment]
@maxleiko: is that fixed?

**Comment by maxleiko** [comment]
Yes https://github.com/kevoree/kevoree-js/commit/70b22c35b8be938a29d086152053739d7cedac08

(and using a proper shell on Windows)
