### ISSUE TITLE
Improve continuous integration of plugins

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#58]
ThingML plugins should be automatically built on the server, including the jar in /lib so that we do not need to do it manually.

**Comment by brice-morin** [comment]
We need this script:
```
cd org.thingml.editor.standaloneApp
mvn -f pom_eclipse.xml clean install
cp target/org.thingml.editor.standaloneApp-0.6.0-SNAPSHOT-jar-with-dependencies.jar ../org.thingml.eclipse.ui/lib/
```

It seems it did not really work as a post-build step, since it was executed before the Maven artefact were deployed, and it downloaded "old" jars, etc. It seems it should be a separate job.

**Comment by barais** [comment]
Only for ThingML ?

do you want that I build ThingML on coreff ?

**Comment by brice-morin** [comment]
Well, for now, we have a script (.bat, but I guess a .sh would be fairly similar) that builds the "big jar" locally and move it into the lib folder of the plugin. Then we commit everything and plugin should be up to date. The idea would be to run the script on the jenkins. In principle it is very easy, in practice, it probably needs some tweaking.

**Comment by brice-morin** [comment]
This is greatly with the new parser (currently in xtext branch, to be merge in master soon)
