### ISSUE TITLE
JS error when calling out to function in on entry statement 

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#62]
The following causes an error in the generated JS:

Error: 
_this.initialize();
^
ReferenceError: _this is not defined
    at SensorJS._init (C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml
-gen\javascript\FieldNode\SensorJS.js:149:1)
    at Object.<anonymous> (C:\Users\KnutEilif\Heads_13.02\workspace\Training\thi
ngml-gen\javascript\FieldNode\main.js:18:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain [as _onTimeout] (module.js:497:10)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Code:

function initialize() 
    do
        'var m = require(\'mraa\');
         console.log(\'MRAA Version: \' + m.getVersion());
         var analogPin0 = new m.Aio(0); '
    end
    
    function read() : Integer
    do
       'var analogValue = analogPin0.read();
        console.log(analogValue); '
        return 'analogValue'
    end
    
    property value : Integer = 0
    
    statechart SensorMachine init Idle {

        on entry initialize()  <<<<------- Placed here gives error

		state Idle {
			on entry initialize()  <<<<------- Placed here works
			internal event sensor_service?read
			action do
				value = read()
				sensor_service!reading(value)
			end		
			
			transition -> PeriodicReading
			event t : sensor_service?start_periodic_reading
			action do
				delay = t.delay
				timer!timer_start(delay)
			end
			
		}

**Comment by brice-morin** [comment]
OK, I probably fixed the problem. But I have to test in more depth to be sure I did not break anything else... I remember some stuff around "this" in JS were not quite natural for me, coming from Java...

**Comment by brice-morin** [comment]
I guess it should work now. Reopen if not.
