### ISSUE TITLE
Uploading of components to kevoree registry

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#64]
Hi,

Do you have a short tutorial/description on howto upload components to the kevoree registry? I guess this is needed when I am going to start with empty nodes :-)

**Comment by maxleiko** [comment]
You mean upload from a Kevoree (Java/Js) project, or using just a .json ?

**Comment by maxleiko** [comment]
What do you mean by empty nodes ?

**Comment by kehusa** [comment]
Normally when I have started kevoree nodes I have transferred the source to the target device and compiled the source there. Then the component has been installed on the target. I was now thinking that I should start the kevoree node without any components installed on the target device in advance. Then I take it I have to download the components from the kevoree registry.

**Comment by kehusa** [comment]
I was using the wrong word, not kevoree registry but kevoree repository. Sorry.

**Comment by maxleiko** [comment]
Oh ok, in java when you deploy your code to a maven repo there is a Kevoree plugin that is triggered and does the registry publishing for you.

**Comment by maxleiko** [comment]
There is two things:
  - you want your .jar to be available for anybody
  - you want your TypeDefinition to be accessible for anybody in a KevScript

So, for the first one, you have to deploy your .jar on a Maven repository.
For the second one, your kevoree model must be pushed on the Kevoree registry.

In a Kevoree Java project, if you take look to the available plugins, you will see that there is `kev:deploy` (and the already known `kev:run`, and `kev:generate`)
The `kev:deploy` is triggered when you do a `mvn deploy` in order to publish your .jar to a maven repo. So it will also publish your `target/classes/KEV-INF/lib.json` model to the Kevoree registry automatically :)

**Comment by kehusa** [comment]
Superb, what about javascript?

**Comment by maxleiko** [comment]
Same thing, but there is no Maven repo, its the npm registry for Node.js modules :)

**Comment by maxleiko** [comment]
When you do an `npm publish` if you look at your `package.json` there is a script that is triggered on `postpublish` that calls the Grunt task `grunt publish`. This is the task that publish your `kevlib.json` model to the Kevoree registry

**Comment by maxleiko** [comment]
Same idea, but with the JS technos :)

**Comment by kehusa** [comment]
Great, and I do no need any login for these repositories?

**Comment by maxleiko** [comment]
You will need auth for both.

**Comment by kehusa** [comment]
Ok, I already have login for npm. You have instructed me previously, but not for java.
How do I get login there?

**Comment by maxleiko** [comment]
For the `npm` registry you need to create an account on their website [here](https://www.npmjs.com/)

For Maven, it's a bit different, you cannot easily gain access to the Maven central repo, well you can, but it won't be today.
We (the Kevoree team), use https://oss.sonatype.org/ which is replicated on Maven central, so it's great.
But in your case, you could run an [Archiva](http://archiva.apache.org/index.cgi) somewhere, it might be easier

**Comment by kehusa** [comment]
Ok, I think I also will use https://oss.sonatype.org/. Thx

**Comment by maxleiko** [comment]
You have to do open-source code, and the process is a bit tedious, but in the end it's way better because you can have access to your Maven dependencies without specifying your repo in your pom.xml because it goes on the central.

**Comment by maxleiko** [comment]
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by kehusa** [comment]
trying to publish my HomeGW component, but keep getting this error:
(I am able to run npm login)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'publish',
1 verbose cli   '--verbose' ]
2 info using npm@1.4.28
3 info using node@v0.10.33
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose publish [ '.' ]
6 verbose cache add [ '.', null ]
7 verbose cache add name=undefined spec="." args=[".",null]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: '.',
8 verbose parsed url   path: '.',
8 verbose parsed url   href: '.' }
9 silly lockFile 3a52ce78- .
10 verbose lock . C:\Users\KnutEilif\AppData\Roaming\npm-cache\3a52ce78-.lock
11 verbose tar pack [ 'C:\\Users\\KnutEilif\\AppData\\Roaming\\npm-cache\\HomeGW\\1.0.1\\package.tgz',
11 verbose tar pack   '.' ]
12 verbose tarball C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package.tgz
13 verbose folder .
14 info prepublish HomeGW@1.0.1
15 verbose unsafe-perm in lifecycle true
16 silly lockFile 1f1177db-tar tar://.
17 verbose lock tar://. C:\Users\KnutEilif\AppData\Roaming\npm-cache\1f1177db-tar.lock
18 silly lockFile 05c8e43a-m-cache-HomeGW-1-0-1-package-tgz tar://C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package.tgz
19 verbose lock tar://C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package.tgz C:\Users\KnutEilif\AppData\Roaming\npm-cache\05c8e43a-m-cache-HomeGW-1-0-1-package-tgz.lock
20 silly lockFile 1f1177db-tar tar://.
21 silly lockFile 1f1177db-tar tar://.
22 silly lockFile 05c8e43a-m-cache-HomeGW-1-0-1-package-tgz tar://C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package.tgz
23 silly lockFile 05c8e43a-m-cache-HomeGW-1-0-1-package-tgz tar://C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package.tgz
24 silly lockFile d2666a2f-g-npm-cache-HomeGW-1-0-1-package C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package
25 verbose lock C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package C:\Users\KnutEilif\AppData\Roaming\npm-cache\d2666a2f-g-npm-cache-HomeGW-1-0-1-package.lock
26 silly lockFile d2666a2f-g-npm-cache-HomeGW-1-0-1-package C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package
27 silly lockFile d2666a2f-g-npm-cache-HomeGW-1-0-1-package C:\Users\KnutEilif\AppData\Roaming\npm-cache\HomeGW\1.0.1\package
28 silly lockFile 3a52ce78- .
29 silly lockFile 3a52ce78- .
30 silly publish { name: 'HomeGW',
30 silly publish   version: '1.0.1',
30 silly publish   description: 'HomeGW configuration generated from ThingML',
30 silly publish   main: 'lib/HomeGW.js',
30 silly publish   private: false,
30 silly publish   dependencies: { 'state.js': '^4.1.5', 'kevoree-entities': '^8.0.0' },
30 silly publish   devDependencies:
30 silly publish    { grunt: '^0.4.1',
30 silly publish      'grunt-kevoree': '^5.0.0',
30 silly publish      'grunt-kevoree-genmodel': '^2.0.0',
30 silly publish      'grunt-kevoree-registry': '^2.0.0' },
30 silly publish   scripts: { prepublish: 'grunt', postpublish: 'grunt publish' },
30 silly publish   kevoree: { package: 'no.tellu' },
30 silly publish   readme: 'Example with Server node receiving Sensor measurements from Field Nodes.\r\nField node is to be deployed on Intel Edison\r\n\r\nCurrently the example reads analog input on pin 0 on a Intel Edison Breakout board\r\n\r\nkevscript files are stored in source files and must replace the automatically genenerated kevscript files.\r\n\r\n',
30 silly publish   readmeFilename: 'README.md',
30 silly publish   _id: 'HomeGW@1.0.1',
30 silly publish   _shasum: 'ec82209b1c39251c0de086b54abac2de908c8d88',
30 silly publish   _from: '.' }
31 verbose request where is /HomeGW
32 verbose request registry https://registry.npmjs.org/
33 verbose request id 821ce221800a8cdd
34 verbose url raw /HomeGW
35 verbose url resolving [ 'https://registry.npmjs.org/', './HomeGW' ]
36 verbose url resolved https://registry.npmjs.org/HomeGW
37 verbose request where is https://registry.npmjs.org/HomeGW
38 info trying registry request attempt 1 at 18:22:37
39 http PUT https://registry.npmjs.org/HomeGW
40 http 401 https://registry.npmjs.org/HomeGW
41 verbose headers { date: 'Thu, 09 Apr 2015 16:22:39 GMT',
41 verbose headers   server: 'Apache',
41 verbose headers   'content-type': 'application/json',
41 verbose headers   'cache-control': 'max-age=60',
41 verbose headers   'content-length': '38',
41 verbose headers   'accept-ranges': 'bytes',
41 verbose headers   via: '1.1 varnish',
41 verbose headers   'x-served-by': 'cache-ams4123-AMS',
41 verbose headers   'x-cache': 'MISS',
41 verbose headers   'x-cache-hits': '0',
41 verbose headers   'x-timer': 'S1428596556.727361,VS0,VE2408',
41 verbose headers   'keep-alive': 'timeout=10, max=50',
41 verbose headers   connection: 'Keep-Alive' }
42 error publish Failed PUT 401
43 error Error: Request was not authorized : HomeGW
43 error     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:308:14)
43 error     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:246:65)
43 error     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:236:22)
43 error     at Request.emit (events.js:98:17)
43 error     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1142:14)
43 error     at Request.emit (events.js:117:20)
43 error     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1096:12)
43 error     at IncomingMessage.emit (events.js:117:20)
43 error     at _stream_readable.js:943:16
43 error     at process._tickCallback (node.js:419:13)
44 error If you need help, you may report this *entire* log,
44 error including the npm and node versions, at:
44 error     <http://github.com/npm/npm/issues>
45 error System Windows_NT 6.2.9200
46 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--verbose"
47 error cwd C:\Users\KnutEilif\Heads_13.02\workspace\Training\thingml-gen\javascript\HomeGW
48 error node -v v0.10.33
49 error npm -v 1.4.28
50 verbose exit [ 1, true ]

**Comment by maxleiko** [comment]
It is not allowed to use upper case for module name

**Comment by kehusa** [comment]
That fixed it :-) But do I need to reference the module name in kevscript file?

**Comment by maxleiko** [comment]
No module name, just the TypeDefinition
