### ISSUE TITLE
Retry connection with master server

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#68]
When trying to establish initial contact with master the node fails if connection is lost as can be seen from the log below.  Shouldn't the node automatically try to reestablish contact with master after some time?

root@ubilinux:/home/heads/demo# sudo ./start.sh
root@ubilinux:/home/heads/demo# nohup: ignoring input and redirecting stderr to stdout
tail -F log.out
00:00:40 ALL KevoreeLogger Set logLevel= info
00:00:40 INFO KevoreeCore Platform node name: node-643
21:05:26 ALL KevoreeLogger Set logLevel= info
21:05:52 INFO WSGroup Lost connection with master "node0" at ws://10.10.0.1:9000
<.. nothing more happens before restart..>
21:16:28 ALL KevoreeLogger Set logLevel= info
21:16:28 INFO KevoreeCore Platform node name: node-197
21:16:41 ALL KevoreeLogger Set logLevel= info
21:16:42 INFO WSGroup "sync" connected to master server ws://10.10.0.1:9000

**Comment by maxleiko** [comment]
There is a mechanism of reconnection already [(here)](https://github.com/kevoree/kevoree-js-group-ws/blob/master/lib/ClientHandler.js#L55)  
Can you tell me more about your use-case so I can try to reproduce something ?

**Comment by maxleiko** [comment]
@kehusa I've made some tests with the master server in a docker container on another network and the reconnection mechanism works apparently.

**Comment by kehusa** [comment]
Maybe we can have a look at it in Rennes. It happens quote often during
initialization.

man. 7. sep. 2015, 10.47 skrev Maxime Tricoire <notifications@github.com>:

**Comment by maxleiko** [comment]
Can we close this?

**Comment by kehusa** [comment]
Yes

fre. 29. jan. 2016, 12:53 skrev Maxime Tricoire <notifications@github.com>:
