### ISSUE TITLE
Programatically updating Kevoree attributes is not allowed

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#75]
My problem. I have a ThingML component wrapped into a Kevoree component, and want to synchronize attributes between the two. When a Kevoree attribute is updated, I want to update the corresponding ThingML attribute (this works using `this.dictionary.on`). However, when the ThingML component updates an attribute, I would like to reflect that into the Kevoree component. It seems that using `this.dictionary.setValue('myAtt', myValue)` fails: `Fatal error: This model is ReadOnly. Elements are not modifiable.`

Am I doing something wrong?

**Comment by maxleiko** [comment]
You are trying to modify the model while it's deploying. This is not permitted. On a deployment phase the model is ReadOnly.
If you want to do that, you will have to do it after the deployment.

**Comment by brice-morin** [comment]
Ok... I will try to put that code some other places... Note that (if I remember well, I have to double check) it was crashing the whole thing. I would have expected a warning rather than error...

**Comment by brice-morin** [comment]
Now I get a `Fatal error: Object [object Object] has no method 'createDictionaryValue'

`

**Comment by maxleiko** [comment]
You can register a listener on the event `deployed` on the core.

```js
start: function (done) {
  // do something
  this.core.on('deployed', function () {
    // called when the deployment phase is done
  });
}
```

What are you trying to do when you say "update the value in Kevoree" ?  
Because, what you *should* do, is modify the model, and then ask for an adaptation. You **should** never try to modify the dictionary values manually. It must be done by the adaptation engine.  
In order to update the model in `kevoree-js`, you can call the `deploy` method on the `this.core` object.

**Comment by brice-morin** [comment]
Right... is there some documentation somewhere on:

- how to get the current model (from the component itself, *i.e* JS code)
- update the model, in particular updating the value of an entry in the dictionary

Actually, it seems I need to re-implement the setValue method.... but probably working on a copy of the current model, or something like this...

**Comment by maxleiko** [comment]
What you want to achieve is just modifying a value of an attribute in an in-memory model, and then send this model to the core so that it deploys it (if I understood correctly):

```js
// get the current model (you must be outside of the deployment phase here)
var model = this.core.getCurrentModel();
var attrVal = model.findByPath('path[to]/your[value]');
attrVal.value = 'newVal';
this.core.deploy(model, function () {
  // modification has been made
});
```

**Comment by maxleiko** [comment]
Something like this should be right. Because you might not know the exact path.

```js
// get your instance in the model
var instance = this.getModelEntity();
var attrVal = instance.dictionary.findValuesById('yourAttrName');
attrVal.value = 'someValue';
```

**Comment by brice-morin** [comment]
Hmmmm...

In your last code snippet, it seems `instance.dictionary` is `null`...

**Comment by maxleiko** [comment]
Can you share your project so I can have a look at it ?

**Comment by brice-morin** [comment]
Sent you by e-mail

**Comment by brice-morin** [comment]
OK, using submitScript(myKevScript) proved to be a good solution. Thanks for the help!
