### ISSUE TITLE
Analog input pins on Arduino

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#76]
Analog pin A0 is not accepted as input pin in ThingML: 
property SoundPin : UInt8 = A0 gives error
Reading e.g. http://www.instructables.com/id/How-to-add-6-extra-pins-to-your-Arduino-with-no-ex/
states that pin A0 equals pin 14, but this trying with exchanging A0 with pin 14 gives no success.

Please advice how to use analog pin A0 in Arduino.

**Comment by Lyadis** [comment]
You should try 
```
property SoundPin : UInt8 = 'A0'
```
A0 is not defined in ThingML but it is in the arduino library in c. So you want it to be interpreted by the c compiler and not the thingml compiler.

**Comment by kehusa** [comment]
thanks, that was obvious when you just mentioned it.

2015-11-03 15:19 GMT+01:00 Nicolas Harrand <notifications@github.com>:

> You should try
>
> property SoundPin : UInt8 = 'A0'
>
> A0 is not defined in ThingML but it is in the arduino library in c. So you
> want it to be interpreted by the c compiler and not the thingml compiler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEADS-project/heads_ide/issues/76#issuecomment-153368834>
> .
>



-- 
| Knut Eilif Husa | Tellu AS | Lensmannslia 4, 1386 Asker - NORWAY| Direct:
+47 452 49496 | www.tellu.no |

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by Lyadis** [comment]
No problem

**Comment by brice-morin** [comment]
@kehusa, please assign @Lyadis for future Arduino/C issues :-)
