### ISSUE TITLE
NodeJS code generator generating non runnable code

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#77]
When compiling Tellu Fieldnode project some debug code that is not runnable is generated:
E.g
`
the following ThingML code
````
function initialize() do
	
	if(not(test)) do	
	   	ble =' require(\'noble\');	   	
	   	
	   	'& ble &'.on(\'stateChange\', function(state) {
	   	console.log(\'stateChange\')'
  		BLEInternal!stateChange('state')'
  		console.log(\'sent state \' +state)	
		});'
		
		''&ble&'.on(\'discover\', function(peripheral) {
		var perStr = JSON.stringify(peripheral, function( key, value) { 
  			if( key == \'_noble\') { return value.id;}
  			else {return value;}
			});'
  		BLEInternal!discover('perStr')'
  		//console.log(\'sent state \' +perStr)	
		});'
		end
		
	end
````
give the following javascript code

```
function initialize() {
if( !((_this.BLE_test__var))) {
if(_this.debug) console.log(colors.magenta(_this.name + "(BLE): property ble changed from " + BLE_ble__var + " to " + ( require('noble');	   	
	   	
	   	_this.BLE_ble__var.on('stateChange', function(state) {
	   	console.log('stateChange'))));
_this.BLE_ble__var =  require('noble');	   	   	
	   	_this.BLE_ble__var.on('stateChange', function(state) {
	   	console.log('stateChange');
setImmediate(sendStateChangeOnBLEInternal, state);
  		console.log('sent state ' +state)	
		});
_this.BLE_ble__var.on('discover', function(peripheral) {
		var perStr = JSON.stringify(peripheral, function( key, value) { 
  			if( key == '_noble') { return value.id;}
  			else {return value;}
			});
setImmediate(sendDiscoverOnBLEInternal, perStr);  			
		});
}
}
````

which gives following error

````
BLE.js:65
property ble changed from " + BLE_ble__var + " to " + ( require('noble');

                                                                        ^
SyntaxError: Unexpected token ;
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\KnutEilif\Heads_13.02\workspace\Training\thi
ngml-gen\nodejs\FieldNode\main.js:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

````

**Comment by brice-morin** [comment]
I think this is already fixed, but not yet released in the plugins.

**Comment by brice-morin** [comment]
See SINTEF-9012/ThingML#98

**Comment by kehusa** [comment]
That is fine :-)

When are you planning to release the plugin with the fix? Currently I have to manually remove the statements from the generated code.

**Comment by brice-morin** [comment]
Well, I can release it any time, basically. And we have a set of new features, like internal ports. But we should make sure we release them at a not too critical period (to avoid problems if it is some unpredictable and hard to test regressions e.g. in the plugins like last time). Or you can make sure you have a backup HEADS IDE that works.

**Comment by kehusa** [comment]
That is probably a good idea. I make a copy of my entire working
environment before I upgrade. For me, you can then just go ahead :-)


2015-11-09 12:20 GMT+01:00 Brice Morin <notifications@github.com>:

> Well, I can release it any time, basically. And we have a set of new
> features, like internal ports. But we should make sure we release them at a
> not too critical period (to avoid problems if it is some unpredictable and
> hard to test regressions e.g. in the plugins like last time). Or you can
> make sure you have a backup HEADS IDE that works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HEADS-project/heads_ide/issues/77#issuecomment-155031980>
> .
>



-- 
| Knut Eilif Husa | Tellu AS | Lensmannslia 4, 1386 Asker - NORWAY| Direct:
+47 452 49496 | www.tellu.no |

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by brice-morin** [comment]
OK, update site for ThingML should be up-to-date in 10 minutes or so. You can use it to update (another) HEADS IDE. I did not rebuild the whole HEADS IDE yet.
