### ISSUE TITLE
Error when running MQTTComponent

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#78]
sent state poweredOn
Start scanning receivedSensor ReadingThingML attribute FieldNode_sensor_SensorJS_value__var updated...
updating Kevoree attribute...

/home/heads/demo/node_modules/field-node/node_modules/kevoree-entities/lib/KevoreeEntity.js:153
this.getKevoreeCore().submitScript(script, callback);
^
TypeError: Object KevoreeCore has no method 'submitScript'
at PseudoClass.Class.submitScript (/home/heads/demo/node_modules/field-node/node_modules/kevoree-entities/lib/KevoreeEntity.js:153:31)
at PseudoClass.<anonymous> (/home/heads/demo/node_modules/field-node/lib/FieldNode.js:225:6)
at /home/heads/demo/node_modules/field-node/lib/SensorJS.js:455:36
at /home/heads/demo/node_modules/field-node/node_modules/state.js/lib/state.com.js:51:61
at Array.forEach (native)
at Behavior.invoke (/home/heads/demo/node_modules/field-node/node_modules/state.js/lib/state.com.js:51:26)
at traverse (/home/heads/demo/node_modules/field-node/node_modules/state.js/lib/state.com.js:1070:20)
at evaluateState (/home/heads/demo/node_modules/field-node/node_modules/state.js/lib/state.com.js:1047:26)
at /home/heads/demo/node_modules/field-node/node_modules/state.js/lib/state.com.js:1030:17
at Array.every (native)

**Comment by brice-morin** [comment]
Hmmmm, it could be related to one of the new feature we introduced in the ThingML->KevoreeJS compiler related to the update of attributes (so that Kevoree dictonary attributes are in sync, on both ways, with ThingML attributes)... I guess I and @maxleiko have to investigate a bit...

**Comment by brice-morin** [comment]
Well, I re-tested again (on a simple example though) and that new feature (indeed using submitScript) works....

**Comment by brice-morin** [comment]
And I just tried the FieldNode (on my PC, not on Edison) and the new feature works... I would suggest re-generate the whole JS from scratch to see if it helps (and remove all the node_modules and deploy units.

**Comment by maxleiko** [comment]
Agree. Remove both `.deploy_units` and `node_modules` and re-install / re-start. Should be good.

**Comment by kehusa** [comment]
OK, did so but now I get this:
````
12:03:11 ALL KevoreeLogger Set logLevel= info
12:03:21 INFO KevoreeCore Platform node name: node-732

> ws@0.4.32 install /home/heads/demo/node_modules/kevoree-group-ws/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/heads/demo/node_modules/kevoree-group-ws/node_modules/ws/build'
CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
SOLINK_MODULE(target) Release/obj.target/bufferutil.node
SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
COPY Release/bufferutil.node
CXX(target) Release/obj.target/validation/src/validation.o
SOLINK_MODULE(target) Release/obj.target/validation.node
SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
COPY Release/validation.node
make: Leaving directory `/home/heads/demo/node_modules/kevoree-group-ws/node_modules/ws/build'
kevoree-group-ws@5.2.10 node_modules/kevoree-group-ws
├── shortid@2.2.4
├── pseudoclass@1.0.3
├── smart-socket@0.2.1 (async@0.9.2)
├── kevoree-entities@8.1.0 (kevoree-commons@2.2.0)
├── kevoree-library@5.0.9 (kevoree-kotlin@1.0.3)
├── ws@0.4.32 (tinycolor@0.0.1, options@0.0.6, commander@2.1.0, nan@1.0.0)
└── kevoree-kevscript@2.2.3 (waxeye@0.8.1, kevoree-kotlin@1.0.3, async@0.9.2, chalk@0.5.1, semver@4.3.6, kevoree-commons@2.2.0, optimist@0.6.1, kevoree-registry-client@2.2.2)
12:03:57 ALL KevoreeLogger Set logLevel= info
12:03:57 INFO WSGroup "sync" connected to master server ws://10.10.0.1:9000
12:04:01 WARN KevoreeCore New deploy process requested: aborted because another one is in process (retry later?)

````

**Comment by brice-morin** [comment]
@maxleiko @kehusa what is the status here?

**Comment by maxleiko** [comment]
@brice-morin I forgot a call to `done()` in the **WSGroup** `start(done)` method. So the adaptation timed-out.
=> Fixed in 5.2.11-SNAPSHOT and above

**Comment by brice-morin** [comment]
@maxleiko has it been released properly?

**Comment by maxleiko** [comment]
Yes. We are in 5.3.1 now
