### ISSUE TITLE
Kevoree dictionary attribute not generated

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#80]
Trying to generate a dictionary attribute from ThingML file Properties.thingml file that is included in other things, fails. The rationale to do it this way was to have some system globally defined properties that could be included where needed.

The code is:
````
import "datatypes.thingml"

thing fragment Properties {
	property nodeName : String = "FN1"  @kevoree "true"
}
````

**Comment by brice-morin** [comment]
OK, I will investigate

**Comment by kehusa** [comment]
The strange thing is that the attributes seems to be generated from one thing but not from another.
Might be a clue

**Comment by brice-morin** [comment]
OK, that was easy, just add 

`@java_primitive "true"` to the `String` datatype in `datatypes.thingml`

We only allow primitive types to be expose + String should also be allowed. Even though String in Java is not exactly primitive we can somehow handle it as a primitive type

> Note however that the `Properties` thing seems to be included by many thing that are instantiated in the configuration which we wrap as a Kevoree component, meaning you will have several `***nodeName` attributes in your Kevoree component. If that is problematic and would rather like to have one global node name attribute... please open another issue :-)
