### ISSUE TITLE
Persistency in kevoree

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#82]
When updating models and attributes, I experience that these are persistently stored when switching off and on the device of the sync master. Is this correct? If I want to remove the model, how do I delete it from the sync master?

**Comment by maxleiko** [comment]
The WSGroup always merges models from new clients. So if you cut the master, and still keep one client up and running, then when you re-start the master node you should get a merge with the old model of that client and the current one of the group.  
This behavior might give what you call persistence.  
Is this what's happening ? Clients are still running while master restarts ?

**Comment by kehusa** [comment]
Ok, I guess that this is actually what happens. Thanks.
