### ISSUE TITLE
ThingML / Kevoree port mapping

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#84]
Currently, in ThingML/KevoreeJS, ThingML ports are systematically split (to avoid serializaing metadata for routing and allow connection to external services). In the case where two Kevoree ports are actually connected to HEADS component, we should not split ports and serialize those metadata.

Mapping policy:
- non connected standard port will not be split
- port connected with an external connector over kevoree will be split

**Comment by brice-morin** [comment]
@kehusa would that be ok?

**Comment by brice-morin** [comment]
@kehusa can you test? As I mentionned in my commit message, I did not test in depth. I can try to test a bit more tomorrow...

**Comment by kehusa** [comment]
I will do.

ons. 9. des. 2015, 16:27 skrev Brice Morin <notifications@github.com>:

**Comment by brice-morin** [comment]
Obviously, it still needs some work. I'll notify you when you can test.

**Comment by brice-morin** [comment]
By default, port are not split
To split a port (and expose raw data without serialization overhead):
```
    connector myInstance.myPort over kevoree  
```
