### ISSUE TITLE
Kevoree MQTT onTopicAndMsg serialisation

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#88]
When receiving messages from MQTTSubClient on port onTopicAndMsg I get the following content: ```{"topic":"sensor/button","message":{"type":"Buffer","data":[49,48,50]}}```
The topic part is ok, but I don't understand how to deal with the message part

When receiving messages from MQTTSubClient on port onMsg I get:
```102 ```(which is what I expect)

Why is the serialisation different?

**Comment by brice-morin** [comment]
Is the raw data OK in the code generated from ThingML? Is it still OK just before sending on the Kevoree port?

**Comment by kehusa** [comment]
ThingML does not make any changes to the message content. It is equal on the MQTTSubClient port and inside the ThingML component.

**Comment by maxleiko** [comment]
@kehusa  do you use the Java or the Javascript version of the MQTTSubClient ?

**Comment by maxleiko** [comment]
MQTTSubClient v2.0.2 should fix this issue.

**Comment by kehusa** [comment]
tested and works, thanks
