### ISSUE TITLE
Unable to add filter attribute in kevscript editor

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#94]
When specifying a filter attribute in kevscript editor, this error is displayed: 
Unknown attribute "filter" in /groups[sync] (set sync.filter = "^FN[1-2]$")

**Comment by maxleiko** [comment]
Be sure to specify the `5.3.2-SNAPSHOT` in the KevScript as it is the only available version that supports the `filter` attribute

**Comment by kehusa** [comment]
The problem is not the javascript node, it is the kevscript editor that
gives the error when I press the merge button.

2016-06-27 11:13 GMT+02:00 Maxime Tricoire <notifications@github.com>:

> Be sure to specify the 5.3.2-SNAPSHOT in the KevScript as it is the only
> available version that supports the filter attribute
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HEADS-project/heads_ide/issues/94#issuecomment-228693083>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIN553877VFsdQzYtOYaQyRrot-WdSvZks5qP5RJgaJpZM4I-4-m>
> .
>



-- 
| Knut Eilif Husa | Tellu AS | Lensmannslia 4, 1386 Asker - NORWAY| Direct:
+47 452 49496 | www.tellu.no |

This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system.

**Comment by maxleiko** [comment]
The KevScript editor gives this error if it cannot find the `filter` param in the TypeDefinition of the instance. But I've made a test, and it works if you use the `5.3.2-SNAPSHOT` of `WSGroup`

**Comment by maxleiko** [comment]
The new version of the KevScript editor will display better error messages.
