### ISSUE TITLE
Usage of internal ports

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#97]
In order to use internal ports, i.e. sending to self,  is there any annotation of the port needed, or is it just to send and receive to it?

**Comment by brice-morin** [comment]
``` 
internal port myPort {
   sends a, b, c
   receives a, b, c
}
```

then use the port in your state machine as a normal port on which you can send message and on which you can have events waiting for a message to be received.

You should not connect internal ports in your configuration. This will be done automatically

**Comment by brice-morin** [comment]
Note that when the new parser is there, we might simplify the syntax of internal port, to avoid duplicating the list of messages in send/receive (since you want to receive what you are able to send on an internal port), which is redundant information.
