### ISSUE TITLE
Generate Kevoree debug traces when a message is sent through a port without channel

### ISSUE THREAD

**Issue by brice-morin** [HEADS-project/heads_ide#98]
It would be good to generate some `Message XXX lost because port YYY is dangling` debug traces. Indeed, when components have a few provided and required ports, it can be easy not to connected the proper ones and leave the important ones dangling. Those debug traces would help. Isn't it @kehusa ? ;-)

**Comment by kehusa** [comment]
I agree

Den tir. 16. aug. 2016, 21:48 skrev Brice Morin <notifications@github.com>:

**Comment by maxleiko** [comment]
Yep, I've done that in Java for the next version to come, will also do that for Js
