### ISSUE TITLE
UML generation of Things with sessions

### ISSUE THREAD

**Issue by kehusa** [HEADS-project/heads_ide#99]
I get an error when trying to generate UML diagrams from Things with sessions.
Is it possible to visualize this behavior?

**Comment by brice-morin** [comment]
Not supported yet. I guess I could consider them as normal regions in the visualizations. I do not really have the time today, but will try to fix that soon.

**Comment by brice-morin** [comment]
Should work now. I tried on the TellU models and it seems to work.
